# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SuperCollider-nbdev',
                'doc_host': 'https://twistin.github.io',
                'git_url': 'https://github.com/twistin/SuperCollider-nbdev',
                'lib_path': 'SuperCollider_nbdev'},
  'syms': {'SuperCollider_nbdev.core': {'SuperCollider_nbdev.core.foo': ('core.html#foo', 'SuperCollider_nbdev/core.py')}}}
